---
title: IBMQAccountError (v0.28)
description: API reference for qiskit.providers.ibmq.IBMQAccountError in qiskit v0.28
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountError
---

<span id="qiskit-providers-ibmq-ibmqaccounterror" />

# qiskit.providers.ibmq.IBMQAccountError

<Class id="qiskit.providers.ibmq.IBMQAccountError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.15/qiskit/providers/ibmq/exceptions.py" signature="IBMQAccountError(*message)" modifiers="exception">
  Base class for errors raised by account management.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.IBMQAccountError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

