---
title: PulseError (v0.28)
description: API reference for qiskit.pulse.PulseError in qiskit v0.28
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.pulse.PulseError
---

<span id="qiskit-pulse-pulseerror" />

# qiskit.pulse.PulseError

<Class id="qiskit.pulse.PulseError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit/tree/stable/0.18/qiskit/pulse/exceptions.py" signature="PulseError(*message)" modifiers="exception">
  Errors raised by the pulse module.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.pulse.PulseError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

