---
title: CredentialsError
description: API reference for qiskit.providers.ibmq.credentials.CredentialsError
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.credentials.CredentialsError
---

<span id="qiskit-providers-ibmq-credentials-credentialserror" />

# qiskit.providers.ibmq.credentials.CredentialsError

<Class id="qiskit.providers.ibmq.credentials.CredentialsError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/credentials/exceptions.py" signature="CredentialsError(*message)" modifiers="exception">
  Base class for errors raised during credential management.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.credentials.CredentialsError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

