---
title: IBMQAccountMultipleCredentialsFound
description: API reference for qiskit.providers.ibmq.IBMQAccountMultipleCredentialsFound
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountMultipleCredentialsFound
---

<span id="qiskit-providers-ibmq-ibmqaccountmultiplecredentialsfound" />

# qiskit.providers.ibmq.IBMQAccountMultipleCredentialsFound

<Class id="qiskit.providers.ibmq.IBMQAccountMultipleCredentialsFound" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/exceptions.py" signature="IBMQAccountMultipleCredentialsFound(*message)" modifiers="exception">
  Errors raised when multiple credentials are found.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.IBMQAccountMultipleCredentialsFound.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

