---
title: InvalidCredentialsFormatError
description: API reference for qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError
---

<span id="qiskit-providers-ibmq-credentials-invalidcredentialsformaterror" />

# qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError

<Class id="qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/credentials/exceptions.py" signature="InvalidCredentialsFormatError(*message)" modifiers="exception">
  Errors raised when the credentials are in an invalid format.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

