---
title: IBMQAccountCredentialsInvalidUrl
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl
---

<span id="qiskit-providers-ibmq-ibmqaccountcredentialsinvalidurl" />

# qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl

<Class id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/exceptions.py" signature="IBMQAccountCredentialsInvalidUrl(*message)" modifiers="exception">
  Errors raised when an IBM Quantum Experience URL is invalid.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

